// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231108092604_nowaMigracjaZxc")]
    partial class nowaMigracjaZxc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06.Shared.Films.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "7",
                            Director = "Judyta Niedzielski",
                            Price = 947.599053739383m,
                            ReleaseDate = new DateTime(2023, 3, 22, 4, 3, 32, 987, DateTimeKind.Local).AddTicks(3668),
                            Title = "id"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "0",
                            Director = "Weronika Jaros",
                            Price = 515.587012653512m,
                            ReleaseDate = new DateTime(2023, 2, 17, 2, 35, 58, 334, DateTimeKind.Local).AddTicks(158),
                            Title = "eos"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "4",
                            Director = "Olga Dudek",
                            Price = 987.740517770285m,
                            ReleaseDate = new DateTime(2023, 9, 25, 14, 7, 51, 729, DateTimeKind.Local).AddTicks(4688),
                            Title = "ratione"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "9",
                            Director = "Rajnold Wójtowicz",
                            Price = 944.895053455557m,
                            ReleaseDate = new DateTime(2023, 4, 15, 14, 30, 31, 365, DateTimeKind.Local).AddTicks(676),
                            Title = "unde"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Director = "Lea Stanek",
                            Price = 419.498144894139m,
                            ReleaseDate = new DateTime(2023, 4, 30, 3, 50, 8, 599, DateTimeKind.Local).AddTicks(6117),
                            Title = "aspernatur"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "4",
                            Director = "Anna Mroczek",
                            Price = 511.754347763376m,
                            ReleaseDate = new DateTime(2023, 4, 3, 11, 38, 43, 149, DateTimeKind.Local).AddTicks(7685),
                            Title = "officiis"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "0",
                            Director = "Gerald Gajda",
                            Price = 772.394792875459m,
                            ReleaseDate = new DateTime(2023, 4, 21, 2, 44, 58, 569, DateTimeKind.Local).AddTicks(4465),
                            Title = "aut"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "5",
                            Director = "Lilianna Kogut",
                            Price = 379.654358614075m,
                            ReleaseDate = new DateTime(2023, 5, 17, 6, 39, 14, 805, DateTimeKind.Local).AddTicks(9523),
                            Title = "voluptatibus"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "2",
                            Director = "Ireneusz Graczyk",
                            Price = 91.5445527781474m,
                            ReleaseDate = new DateTime(2023, 9, 22, 17, 50, 38, 315, DateTimeKind.Local).AddTicks(6585),
                            Title = "aut"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Director = "Nina Domagała",
                            Price = 153.856289495647m,
                            ReleaseDate = new DateTime(2023, 1, 11, 17, 49, 17, 101, DateTimeKind.Local).AddTicks(7794),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "8",
                            Director = "Gilbert Michałek",
                            Price = 395.184917387173m,
                            ReleaseDate = new DateTime(2023, 2, 22, 19, 38, 36, 855, DateTimeKind.Local).AddTicks(2218),
                            Title = "amet"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "5",
                            Director = "Maurycy Grześkowiak",
                            Price = 910.073467519634m,
                            ReleaseDate = new DateTime(2023, 10, 18, 16, 28, 50, 779, DateTimeKind.Local).AddTicks(3410),
                            Title = "dicta"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "4",
                            Director = "Tymoteusz Mazurek",
                            Price = 809.626763897774m,
                            ReleaseDate = new DateTime(2023, 6, 14, 10, 45, 45, 610, DateTimeKind.Local).AddTicks(2424),
                            Title = "voluptas"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "2",
                            Director = "Arnold Wolski",
                            Price = 49.1675051041727m,
                            ReleaseDate = new DateTime(2023, 5, 29, 2, 34, 14, 907, DateTimeKind.Local).AddTicks(6693),
                            Title = "sed"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "0",
                            Director = "Klara Tomaszewski",
                            Price = 984.268335762093m,
                            ReleaseDate = new DateTime(2023, 8, 19, 7, 21, 54, 182, DateTimeKind.Local).AddTicks(395),
                            Title = "dolores"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "0",
                            Director = "Salomon Żak",
                            Price = 476.815506478686m,
                            ReleaseDate = new DateTime(2023, 3, 19, 13, 43, 10, 911, DateTimeKind.Local).AddTicks(1572),
                            Title = "delectus"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "5",
                            Director = "Krzysztof Zalewski",
                            Price = 104.973396323143m,
                            ReleaseDate = new DateTime(2023, 1, 9, 2, 6, 29, 41, DateTimeKind.Local).AddTicks(6382),
                            Title = "maxime"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "9",
                            Director = "Emil Biernat",
                            Price = 539.836693972739m,
                            ReleaseDate = new DateTime(2023, 4, 12, 3, 14, 10, 920, DateTimeKind.Local).AddTicks(7982),
                            Title = "laudantium"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "2",
                            Director = "Walentyna Barański",
                            Price = 646.066352349737m,
                            ReleaseDate = new DateTime(2023, 10, 27, 18, 28, 34, 645, DateTimeKind.Local).AddTicks(7361),
                            Title = "neque"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Director = "Serafina Krukowski",
                            Price = 434.027346356785m,
                            ReleaseDate = new DateTime(2022, 11, 13, 3, 26, 30, 288, DateTimeKind.Local).AddTicks(3523),
                            Title = "quo"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "3",
                            Director = "Józefina Borowski",
                            Price = 526.597836321498m,
                            ReleaseDate = new DateTime(2023, 4, 2, 4, 20, 0, 527, DateTimeKind.Local).AddTicks(297),
                            Title = "iure"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "9",
                            Director = "Oliwier Cygan",
                            Price = 205.234299416297m,
                            ReleaseDate = new DateTime(2023, 5, 14, 12, 29, 12, 251, DateTimeKind.Local).AddTicks(8085),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "3",
                            Director = "Herman Miśkiewicz",
                            Price = 445.039092507697m,
                            ReleaseDate = new DateTime(2023, 10, 26, 21, 27, 4, 291, DateTimeKind.Local).AddTicks(8285),
                            Title = "necessitatibus"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "1",
                            Director = "Gedeon Jędrzejczak",
                            Price = 656.56568970511m,
                            ReleaseDate = new DateTime(2023, 8, 3, 2, 34, 21, 258, DateTimeKind.Local).AddTicks(8255),
                            Title = "rerum"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "2",
                            Director = "Joanna Zalewski",
                            Price = 435.805003520476m,
                            ReleaseDate = new DateTime(2023, 3, 30, 0, 20, 59, 820, DateTimeKind.Local).AddTicks(5110),
                            Title = "et"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "6",
                            Director = "Szymon Wilczyński",
                            Price = 278.68493513562m,
                            ReleaseDate = new DateTime(2023, 3, 2, 3, 8, 8, 132, DateTimeKind.Local).AddTicks(6907),
                            Title = "quia"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "0",
                            Director = "Szymon Lipka",
                            Price = 290.113292811957m,
                            ReleaseDate = new DateTime(2023, 6, 17, 12, 11, 8, 600, DateTimeKind.Local).AddTicks(5694),
                            Title = "minus"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "4",
                            Director = "Ernest Sobczak",
                            Price = 921.94751935636m,
                            ReleaseDate = new DateTime(2023, 3, 6, 17, 45, 8, 462, DateTimeKind.Local).AddTicks(3532),
                            Title = "in"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "6",
                            Director = "Laura Zaborowski",
                            Price = 568.042756632922m,
                            ReleaseDate = new DateTime(2023, 2, 6, 6, 37, 37, 797, DateTimeKind.Local).AddTicks(9008),
                            Title = "eius"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "0",
                            Director = "August Malicki",
                            Price = 646.859666733006m,
                            ReleaseDate = new DateTime(2023, 10, 11, 5, 44, 31, 723, DateTimeKind.Local).AddTicks(4921),
                            Title = "sed"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "4",
                            Director = "Koralia Kasprzyk",
                            Price = 384.478124646693m,
                            ReleaseDate = new DateTime(2023, 7, 23, 2, 1, 43, 695, DateTimeKind.Local).AddTicks(4187),
                            Title = "quod"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "5",
                            Director = "Teodor Kołodziejczyk",
                            Price = 147.49753606296m,
                            ReleaseDate = new DateTime(2023, 7, 12, 7, 16, 19, 493, DateTimeKind.Local).AddTicks(5508),
                            Title = "odio"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "2",
                            Director = "Jan Grudzień",
                            Price = 453.685324946738m,
                            ReleaseDate = new DateTime(2023, 5, 14, 1, 28, 55, 127, DateTimeKind.Local).AddTicks(3456),
                            Title = "distinctio"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "1",
                            Director = "Filemon Gutowski",
                            Price = 173.209604492043m,
                            ReleaseDate = new DateTime(2023, 6, 22, 8, 47, 29, 159, DateTimeKind.Local).AddTicks(9288),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "8",
                            Director = "Nazariusz Dudzik",
                            Price = 812.055163684792m,
                            ReleaseDate = new DateTime(2023, 2, 9, 15, 10, 15, 661, DateTimeKind.Local).AddTicks(6433),
                            Title = "est"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "2",
                            Director = "Nestor Wojciechowski",
                            Price = 957.114653999039m,
                            ReleaseDate = new DateTime(2023, 5, 17, 21, 28, 33, 522, DateTimeKind.Local).AddTicks(2882),
                            Title = "expedita"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "4",
                            Director = "Gloria Januszewski",
                            Price = 198.096402854704m,
                            ReleaseDate = new DateTime(2023, 8, 22, 6, 26, 17, 368, DateTimeKind.Local).AddTicks(5487),
                            Title = "ullam"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "5",
                            Director = "Luiza Iwański",
                            Price = 516.931952754004m,
                            ReleaseDate = new DateTime(2023, 4, 5, 19, 20, 1, 546, DateTimeKind.Local).AddTicks(9814),
                            Title = "neque"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "4",
                            Director = "Aleksander Marcinkowski",
                            Price = 831.879927467033m,
                            ReleaseDate = new DateTime(2023, 9, 11, 20, 2, 43, 997, DateTimeKind.Local).AddTicks(577),
                            Title = "repellendus"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "1",
                            Director = "Józefina Pytel",
                            Price = 750.174635401077m,
                            ReleaseDate = new DateTime(2023, 7, 19, 2, 33, 2, 702, DateTimeKind.Local).AddTicks(6764),
                            Title = "quam"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "5",
                            Director = "Anna Podgórski",
                            Price = 465.196982412691m,
                            ReleaseDate = new DateTime(2023, 1, 8, 1, 31, 47, 383, DateTimeKind.Local).AddTicks(2041),
                            Title = "illum"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "7",
                            Director = "Aleksander Szcześniak",
                            Price = 655.146955157233m,
                            ReleaseDate = new DateTime(2023, 10, 27, 9, 25, 50, 449, DateTimeKind.Local).AddTicks(602),
                            Title = "aut"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "8",
                            Director = "Ewelina Dróżdż",
                            Price = 627.662476505927m,
                            ReleaseDate = new DateTime(2022, 12, 30, 1, 56, 26, 738, DateTimeKind.Local).AddTicks(6170),
                            Title = "sit"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "2",
                            Director = "Wilhelmina Wróbel",
                            Price = 156.07502561392m,
                            ReleaseDate = new DateTime(2023, 3, 31, 11, 28, 48, 279, DateTimeKind.Local).AddTicks(1013),
                            Title = "aut"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "9",
                            Director = "Damian Jóźwiak",
                            Price = 505.614110672201m,
                            ReleaseDate = new DateTime(2023, 6, 23, 11, 0, 29, 894, DateTimeKind.Local).AddTicks(3103),
                            Title = "et"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "3",
                            Director = "Ignacy Rybicki",
                            Price = 423.39219746431m,
                            ReleaseDate = new DateTime(2023, 10, 16, 22, 22, 52, 117, DateTimeKind.Local).AddTicks(6428),
                            Title = "nesciunt"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "9",
                            Director = "Antoni Kaczmarczyk",
                            Price = 906.529322539237m,
                            ReleaseDate = new DateTime(2023, 4, 28, 18, 9, 46, 699, DateTimeKind.Local).AddTicks(5828),
                            Title = "sed"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "3",
                            Director = "Pantaleon Krzyżanowski",
                            Price = 753.138725163945m,
                            ReleaseDate = new DateTime(2023, 7, 14, 16, 3, 45, 861, DateTimeKind.Local).AddTicks(9365),
                            Title = "dignissimos"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "5",
                            Director = "Ksawery Florczak",
                            Price = 848.064586180292m,
                            ReleaseDate = new DateTime(2023, 3, 18, 22, 27, 29, 288, DateTimeKind.Local).AddTicks(7094),
                            Title = "vitae"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "2",
                            Director = "Hipolit Żurawski",
                            Price = 390.585544047219m,
                            ReleaseDate = new DateTime(2023, 10, 22, 10, 11, 28, 561, DateTimeKind.Local).AddTicks(3743),
                            Title = "voluptas"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 712.021981759007m,
                            ReleaseDate = new DateTime(2023, 3, 22, 15, 46, 4, 272, DateTimeKind.Local).AddTicks(5162),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 839.010165513032m,
                            ReleaseDate = new DateTime(2023, 10, 2, 12, 24, 37, 908, DateTimeKind.Local).AddTicks(7320),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 198.083692779804m,
                            ReleaseDate = new DateTime(2023, 1, 21, 7, 18, 21, 181, DateTimeKind.Local).AddTicks(9323),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 160.643399712929m,
                            ReleaseDate = new DateTime(2023, 8, 22, 19, 31, 51, 541, DateTimeKind.Local).AddTicks(697),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 359.887736376788m,
                            ReleaseDate = new DateTime(2023, 2, 22, 20, 50, 3, 270, DateTimeKind.Local).AddTicks(6869),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 181.360829243139m,
                            ReleaseDate = new DateTime(2023, 9, 6, 8, 37, 36, 380, DateTimeKind.Local).AddTicks(4144),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 938.297015022625m,
                            ReleaseDate = new DateTime(2023, 4, 7, 7, 49, 48, 790, DateTimeKind.Local).AddTicks(4221),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 6, 30, 23, 4, 16, 478, DateTimeKind.Local).AddTicks(6442),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 249.172251003875m,
                            ReleaseDate = new DateTime(2022, 12, 20, 15, 3, 31, 935, DateTimeKind.Local).AddTicks(3904),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 10, 12, 6, 45, 41, 396, DateTimeKind.Local).AddTicks(6553),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 842.480734222792m,
                            ReleaseDate = new DateTime(2023, 8, 10, 23, 59, 45, 538, DateTimeKind.Local).AddTicks(3709),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.928430071533m,
                            ReleaseDate = new DateTime(2023, 8, 19, 4, 31, 42, 312, DateTimeKind.Local).AddTicks(2409),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 706.948686653259m,
                            ReleaseDate = new DateTime(2023, 7, 19, 9, 45, 11, 231, DateTimeKind.Local).AddTicks(8380),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.262494314584m,
                            ReleaseDate = new DateTime(2023, 1, 12, 22, 57, 49, 719, DateTimeKind.Local).AddTicks(4734),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 378.222576259273m,
                            ReleaseDate = new DateTime(2023, 8, 3, 16, 3, 42, 749, DateTimeKind.Local).AddTicks(1877),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 11, 21, 7, 58, 31, 216, DateTimeKind.Local).AddTicks(724),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 126.128098112125m,
                            ReleaseDate = new DateTime(2023, 6, 30, 22, 20, 2, 794, DateTimeKind.Local).AddTicks(203),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 530.970371435383m,
                            ReleaseDate = new DateTime(2023, 6, 28, 0, 2, 44, 153, DateTimeKind.Local).AddTicks(3252),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 913.003066283186m,
                            ReleaseDate = new DateTime(2022, 11, 21, 11, 20, 43, 732, DateTimeKind.Local).AddTicks(6594),
                            Title = "Sleek Rubber Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 4, 14, 12, 51, 28, 214, DateTimeKind.Local).AddTicks(9856),
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 479.41424090062m,
                            ReleaseDate = new DateTime(2023, 6, 23, 0, 14, 22, 403, DateTimeKind.Local).AddTicks(2231),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 320.499838554068m,
                            ReleaseDate = new DateTime(2023, 2, 2, 19, 41, 44, 672, DateTimeKind.Local).AddTicks(9943),
                            Title = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.915239043029m,
                            ReleaseDate = new DateTime(2023, 6, 4, 13, 31, 51, 991, DateTimeKind.Local).AddTicks(3501),
                            Title = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 6, 6, 8, 11, 220, DateTimeKind.Local).AddTicks(6662),
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.238750720974m,
                            ReleaseDate = new DateTime(2023, 7, 22, 7, 37, 2, 784, DateTimeKind.Local).AddTicks(3104),
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 150.818741621831m,
                            ReleaseDate = new DateTime(2023, 5, 17, 1, 13, 22, 907, DateTimeKind.Local).AddTicks(8363),
                            Title = "Incredible Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 721.773541800572m,
                            ReleaseDate = new DateTime(2023, 2, 5, 13, 16, 58, 903, DateTimeKind.Local).AddTicks(9952),
                            Title = "Gorgeous Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 688.245783060904m,
                            ReleaseDate = new DateTime(2023, 4, 30, 15, 42, 54, 15, DateTimeKind.Local).AddTicks(5170),
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 553.558320945389m,
                            ReleaseDate = new DateTime(2023, 7, 24, 2, 13, 48, 8, DateTimeKind.Local).AddTicks(6469),
                            Title = "Incredible Soft Computer"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 11, 18, 3, 9, 11, 224, DateTimeKind.Local).AddTicks(8248),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 922.479030014704m,
                            ReleaseDate = new DateTime(2023, 10, 14, 1, 35, 0, 421, DateTimeKind.Local).AddTicks(6398),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 7, 24, 21, 22, 26, 360, DateTimeKind.Local).AddTicks(6824),
                            Title = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 955.272407213818m,
                            ReleaseDate = new DateTime(2023, 5, 1, 21, 51, 27, 611, DateTimeKind.Local).AddTicks(2703),
                            Title = "Handcrafted Frozen Keyboard"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 151.982358236323m,
                            ReleaseDate = new DateTime(2022, 11, 28, 15, 7, 15, 450, DateTimeKind.Local).AddTicks(320),
                            Title = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 434.299358334532m,
                            ReleaseDate = new DateTime(2022, 12, 16, 19, 59, 33, 444, DateTimeKind.Local).AddTicks(9994),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "4",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 57.7988712865854m,
                            ReleaseDate = new DateTime(2023, 1, 5, 14, 33, 30, 978, DateTimeKind.Local).AddTicks(1785),
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 883.980300599234m,
                            ReleaseDate = new DateTime(2023, 4, 3, 6, 6, 44, 373, DateTimeKind.Local).AddTicks(9941),
                            Title = "Handcrafted Rubber Shirt"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 822.452619476455m,
                            ReleaseDate = new DateTime(2023, 1, 13, 4, 8, 24, 693, DateTimeKind.Local).AddTicks(1310),
                            Title = "Rustic Granite Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 22.2432652671092m,
                            ReleaseDate = new DateTime(2023, 4, 9, 11, 46, 39, 252, DateTimeKind.Local).AddTicks(6453),
                            Title = "Sleek Granite Chair"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 6, 27, 8, 32, 55, 876, DateTimeKind.Local).AddTicks(4239),
                            Title = "Incredible Rubber Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 533.504530191656m,
                            ReleaseDate = new DateTime(2023, 8, 9, 15, 38, 18, 24, DateTimeKind.Local).AddTicks(6286),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 265.709933652407m,
                            ReleaseDate = new DateTime(2023, 8, 1, 2, 49, 17, 454, DateTimeKind.Local).AddTicks(1594),
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 294.402654204239m,
                            ReleaseDate = new DateTime(2023, 1, 23, 18, 35, 31, 10, DateTimeKind.Local).AddTicks(567),
                            Title = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 741.648888164036m,
                            ReleaseDate = new DateTime(2023, 1, 27, 16, 15, 56, 168, DateTimeKind.Local).AddTicks(8191),
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 825.239833488706m,
                            ReleaseDate = new DateTime(2023, 1, 5, 12, 22, 19, 238, DateTimeKind.Local).AddTicks(9706),
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "1",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 305.894089151124m,
                            ReleaseDate = new DateTime(2023, 5, 10, 17, 4, 30, 798, DateTimeKind.Local).AddTicks(3211),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 778.911179241683m,
                            ReleaseDate = new DateTime(2023, 1, 13, 12, 4, 5, 100, DateTimeKind.Local).AddTicks(6374),
                            Title = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 318.709401070936m,
                            ReleaseDate = new DateTime(2023, 2, 25, 8, 56, 22, 526, DateTimeKind.Local).AddTicks(6009),
                            Title = "Handcrafted Metal Mouse"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 463.195345650052m,
                            ReleaseDate = new DateTime(2023, 4, 10, 13, 38, 26, 128, DateTimeKind.Local).AddTicks(5213),
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 8, 28, 2, 47, 25, 308, DateTimeKind.Local).AddTicks(3889),
                            Title = "Incredible Plastic Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
