// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231108092226_nowaMigracjaAbc")]
    partial class nowaMigracjaAbc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06.Shared.Films.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 137.99403368076m,
                            ReleaseDate = new DateTime(2022, 11, 16, 16, 46, 31, 131, DateTimeKind.Local).AddTicks(1805),
                            Title = "application Spring"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "5",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 159.983136395916m,
                            ReleaseDate = new DateTime(2023, 11, 2, 2, 9, 1, 319, DateTimeKind.Local).AddTicks(9561),
                            Title = "Graphic Interface mobile"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "4",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 464.178101648194m,
                            ReleaseDate = new DateTime(2023, 9, 14, 18, 26, 16, 129, DateTimeKind.Local).AddTicks(4107),
                            Title = "Washington green"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "4",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 103.373405277437m,
                            ReleaseDate = new DateTime(2023, 7, 4, 9, 44, 47, 869, DateTimeKind.Local).AddTicks(9801),
                            Title = "Michigan aggregate"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 185.171873701351m,
                            ReleaseDate = new DateTime(2023, 2, 21, 16, 43, 13, 725, DateTimeKind.Local).AddTicks(6134),
                            Title = "Tajikistan Human"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "6",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 636.874610120372m,
                            ReleaseDate = new DateTime(2023, 4, 28, 5, 40, 48, 407, DateTimeKind.Local).AddTicks(4045),
                            Title = "fuchsia Silver"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 836.622627579431m,
                            ReleaseDate = new DateTime(2022, 11, 12, 23, 25, 27, 928, DateTimeKind.Local).AddTicks(5477),
                            Title = "complexity Buckinghamshire"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "9",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 732.049760168907m,
                            ReleaseDate = new DateTime(2023, 10, 6, 8, 24, 35, 416, DateTimeKind.Local).AddTicks(8017),
                            Title = "Implemented Avon"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 823.990472946777m,
                            ReleaseDate = new DateTime(2023, 9, 1, 8, 51, 39, 903, DateTimeKind.Local).AddTicks(666),
                            Title = "Fresh GB"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 348.630595346275m,
                            ReleaseDate = new DateTime(2023, 8, 15, 8, 35, 39, 913, DateTimeKind.Local).AddTicks(4666),
                            Title = "salmon Belgium"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 284.641160375272m,
                            ReleaseDate = new DateTime(2023, 4, 30, 1, 14, 1, 967, DateTimeKind.Local).AddTicks(6263),
                            Title = "index Intelligent Granite Gloves"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "5",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 988.516240780948m,
                            ReleaseDate = new DateTime(2023, 1, 27, 16, 16, 11, 889, DateTimeKind.Local).AddTicks(5416),
                            Title = "programming Auto Loan Account"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "9",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 431.077884670383m,
                            ReleaseDate = new DateTime(2023, 6, 4, 2, 1, 3, 702, DateTimeKind.Local).AddTicks(782),
                            Title = "Squares Small"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "8",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 108.542628838468m,
                            ReleaseDate = new DateTime(2023, 5, 18, 14, 3, 28, 554, DateTimeKind.Local).AddTicks(629),
                            Title = "Outdoors Tasty Concrete Chips"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "0",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 831.256413208906m,
                            ReleaseDate = new DateTime(2023, 5, 22, 9, 45, 46, 935, DateTimeKind.Local).AddTicks(9368),
                            Title = "Credit Card Account Tasty"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "3",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 928.933693294848m,
                            ReleaseDate = new DateTime(2023, 10, 28, 22, 15, 39, 880, DateTimeKind.Local).AddTicks(8949),
                            Title = "Small Granite Sausages monitoring"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "6",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 793.849044362478m,
                            ReleaseDate = new DateTime(2023, 7, 24, 14, 36, 59, 99, DateTimeKind.Local).AddTicks(8437),
                            Title = "San Marino compressing"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "7",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 604.762392360606m,
                            ReleaseDate = new DateTime(2023, 3, 15, 2, 58, 21, 381, DateTimeKind.Local).AddTicks(7882),
                            Title = "wireless compress"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 751.959149548299m,
                            ReleaseDate = new DateTime(2023, 4, 25, 2, 28, 44, 360, DateTimeKind.Local).AddTicks(7723),
                            Title = "Iraqi Dinar USB"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 934.25062484073m,
                            ReleaseDate = new DateTime(2022, 11, 24, 19, 12, 47, 167, DateTimeKind.Local).AddTicks(9804),
                            Title = "THX Metal"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "3",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 576.897283204783m,
                            ReleaseDate = new DateTime(2023, 3, 6, 13, 11, 49, 35, DateTimeKind.Local).AddTicks(8408),
                            Title = "open-source Burgs"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "0",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 175.95459921004m,
                            ReleaseDate = new DateTime(2023, 5, 10, 15, 5, 23, 981, DateTimeKind.Local).AddTicks(7844),
                            Title = "withdrawal Handmade Frozen Shoes"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "1",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 491.837397094275m,
                            ReleaseDate = new DateTime(2023, 4, 17, 19, 1, 26, 512, DateTimeKind.Local).AddTicks(1404),
                            Title = "SCSI quantifying"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "9",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 211.867760635385m,
                            ReleaseDate = new DateTime(2023, 9, 27, 17, 38, 15, 957, DateTimeKind.Local).AddTicks(5975),
                            Title = "deposit impactful"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "6",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 565.587814644253m,
                            ReleaseDate = new DateTime(2023, 10, 2, 4, 48, 7, 249, DateTimeKind.Local).AddTicks(2561),
                            Title = "Brazilian Real Soft"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 336.597632218431m,
                            ReleaseDate = new DateTime(2023, 2, 12, 13, 30, 34, 846, DateTimeKind.Local).AddTicks(6541),
                            Title = "Clothing redundant"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "3",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 319.707140555003m,
                            ReleaseDate = new DateTime(2023, 2, 23, 5, 34, 6, 429, DateTimeKind.Local).AddTicks(9131),
                            Title = "synthesizing Factors"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "0",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 172.14635290352m,
                            ReleaseDate = new DateTime(2023, 1, 23, 15, 11, 50, 185, DateTimeKind.Local).AddTicks(648),
                            Title = "world-class empower"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "6",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 516.982459043144m,
                            ReleaseDate = new DateTime(2023, 6, 8, 16, 37, 9, 491, DateTimeKind.Local).AddTicks(3615),
                            Title = "Incredible Metal Ball Inverse"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "7",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 224.602481134516m,
                            ReleaseDate = new DateTime(2023, 8, 20, 7, 26, 58, 156, DateTimeKind.Local).AddTicks(9916),
                            Title = "Realigned Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "8",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 44.4279083117973m,
                            ReleaseDate = new DateTime(2023, 3, 8, 11, 32, 39, 873, DateTimeKind.Local).AddTicks(8641),
                            Title = "Incredible implement"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 684.413199580001m,
                            ReleaseDate = new DateTime(2023, 8, 10, 20, 4, 39, 778, DateTimeKind.Local).AddTicks(8708),
                            Title = "Phased Program"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "2",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 148.837258994504m,
                            ReleaseDate = new DateTime(2023, 7, 23, 6, 8, 38, 846, DateTimeKind.Local).AddTicks(7821),
                            Title = "open-source Investor"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "2",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 341.399866206292m,
                            ReleaseDate = new DateTime(2023, 11, 8, 6, 50, 26, 314, DateTimeKind.Local).AddTicks(3370),
                            Title = "Administrator haptic"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "1",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 308.441545524374m,
                            ReleaseDate = new DateTime(2023, 1, 13, 21, 8, 24, 596, DateTimeKind.Local).AddTicks(7213),
                            Title = "service-desk Practical Soft Chicken"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "0",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 22.6627996166529m,
                            ReleaseDate = new DateTime(2023, 1, 11, 18, 37, 14, 93, DateTimeKind.Local).AddTicks(8775),
                            Title = "Credit Card Account Licensed"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "3",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 86.3958210844527m,
                            ReleaseDate = new DateTime(2023, 3, 27, 10, 52, 20, 622, DateTimeKind.Local).AddTicks(3511),
                            Title = "COM withdrawal"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 319.255191839419m,
                            ReleaseDate = new DateTime(2023, 2, 8, 9, 20, 1, 251, DateTimeKind.Local).AddTicks(333),
                            Title = "Concrete Ergonomic Soft Gloves"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 176.530922628255m,
                            ReleaseDate = new DateTime(2023, 6, 22, 3, 56, 55, 755, DateTimeKind.Local).AddTicks(9759),
                            Title = "Handmade Cotton Salad Port"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "0",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 208.619120477056m,
                            ReleaseDate = new DateTime(2023, 3, 14, 15, 17, 16, 810, DateTimeKind.Local).AddTicks(1813),
                            Title = "Home Loan Account Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "9",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 906.529322539237m,
                            ReleaseDate = new DateTime(2023, 4, 28, 18, 6, 8, 940, DateTimeKind.Local).AddTicks(1050),
                            Title = "paradigms Alaska"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "1",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 83.1003850372976m,
                            ReleaseDate = new DateTime(2023, 4, 16, 22, 42, 47, 738, DateTimeKind.Local).AddTicks(5967),
                            Title = "Knoll blockchains"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 996.181928761854m,
                            ReleaseDate = new DateTime(2023, 10, 16, 15, 29, 28, 323, DateTimeKind.Local).AddTicks(5449),
                            Title = "black panel"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "6",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 991.162918264122m,
                            ReleaseDate = new DateTime(2023, 10, 4, 3, 7, 8, 389, DateTimeKind.Local).AddTicks(6962),
                            Title = "Sports & Music SSL"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "8",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 859.376315591566m,
                            ReleaseDate = new DateTime(2022, 12, 5, 21, 36, 19, 942, DateTimeKind.Local).AddTicks(8952),
                            Title = "drive Identity"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "6",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 893.991202085275m,
                            ReleaseDate = new DateTime(2023, 1, 30, 23, 19, 54, 937, DateTimeKind.Local).AddTicks(6797),
                            Title = "strategic deposit"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "9",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 698.066996843585m,
                            ReleaseDate = new DateTime(2023, 3, 11, 5, 48, 2, 974, DateTimeKind.Local).AddTicks(4042),
                            Title = "JBOD Pre-emptive"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "0",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 75.8424568394397m,
                            ReleaseDate = new DateTime(2023, 4, 28, 6, 7, 36, 968, DateTimeKind.Local).AddTicks(8050),
                            Title = "bandwidth-monitored Wyoming"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 314.284327693416m,
                            ReleaseDate = new DateTime(2023, 11, 6, 21, 0, 19, 242, DateTimeKind.Local).AddTicks(6217),
                            Title = "indexing Investor"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "8",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 361.59689627569m,
                            ReleaseDate = new DateTime(2023, 5, 1, 16, 25, 51, 553, DateTimeKind.Local).AddTicks(5441),
                            Title = "Metal Svalbard & Jan Mayen Islands"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 712.021981759007m,
                            ReleaseDate = new DateTime(2023, 3, 22, 15, 42, 26, 513, DateTimeKind.Local).AddTicks(874),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 839.010165513032m,
                            ReleaseDate = new DateTime(2023, 10, 2, 12, 21, 0, 149, DateTimeKind.Local).AddTicks(2990),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 198.083692779804m,
                            ReleaseDate = new DateTime(2023, 1, 21, 7, 14, 43, 422, DateTimeKind.Local).AddTicks(4992),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 160.643399712929m,
                            ReleaseDate = new DateTime(2023, 8, 22, 19, 28, 13, 781, DateTimeKind.Local).AddTicks(6363),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 359.887736376788m,
                            ReleaseDate = new DateTime(2023, 2, 22, 20, 46, 25, 511, DateTimeKind.Local).AddTicks(2536),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 181.360829243139m,
                            ReleaseDate = new DateTime(2023, 9, 6, 8, 33, 58, 620, DateTimeKind.Local).AddTicks(9846),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 938.297015022625m,
                            ReleaseDate = new DateTime(2023, 4, 7, 7, 46, 11, 30, DateTimeKind.Local).AddTicks(9892),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 6, 30, 23, 0, 38, 719, DateTimeKind.Local).AddTicks(2109),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 249.172251003875m,
                            ReleaseDate = new DateTime(2022, 12, 20, 14, 59, 54, 175, DateTimeKind.Local).AddTicks(9572),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 10, 12, 6, 42, 3, 637, DateTimeKind.Local).AddTicks(2220),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 842.480734222792m,
                            ReleaseDate = new DateTime(2023, 8, 10, 23, 56, 7, 778, DateTimeKind.Local).AddTicks(9377),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.928430071533m,
                            ReleaseDate = new DateTime(2023, 8, 19, 4, 28, 4, 552, DateTimeKind.Local).AddTicks(8103),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 706.948686653259m,
                            ReleaseDate = new DateTime(2023, 7, 19, 9, 41, 33, 472, DateTimeKind.Local).AddTicks(4077),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.262494314584m,
                            ReleaseDate = new DateTime(2023, 1, 12, 22, 54, 11, 960, DateTimeKind.Local).AddTicks(383),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 378.222576259273m,
                            ReleaseDate = new DateTime(2023, 8, 3, 16, 0, 4, 989, DateTimeKind.Local).AddTicks(7523),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 11, 21, 7, 54, 53, 456, DateTimeKind.Local).AddTicks(6371),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 126.128098112125m,
                            ReleaseDate = new DateTime(2023, 6, 30, 22, 16, 25, 34, DateTimeKind.Local).AddTicks(5849),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 530.970371435383m,
                            ReleaseDate = new DateTime(2023, 6, 27, 23, 59, 6, 393, DateTimeKind.Local).AddTicks(8895),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 913.003066283186m,
                            ReleaseDate = new DateTime(2022, 11, 21, 11, 17, 5, 973, DateTimeKind.Local).AddTicks(2260),
                            Title = "Sleek Rubber Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 4, 14, 12, 47, 50, 455, DateTimeKind.Local).AddTicks(5498),
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 479.41424090062m,
                            ReleaseDate = new DateTime(2023, 6, 23, 0, 10, 44, 643, DateTimeKind.Local).AddTicks(7870),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 320.499838554068m,
                            ReleaseDate = new DateTime(2023, 2, 2, 19, 38, 6, 913, DateTimeKind.Local).AddTicks(5582),
                            Title = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.915239043029m,
                            ReleaseDate = new DateTime(2023, 6, 4, 13, 28, 14, 231, DateTimeKind.Local).AddTicks(9138),
                            Title = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 6, 6, 4, 33, 461, DateTimeKind.Local).AddTicks(2301),
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.238750720974m,
                            ReleaseDate = new DateTime(2023, 7, 22, 7, 33, 25, 24, DateTimeKind.Local).AddTicks(8743),
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 150.818741621831m,
                            ReleaseDate = new DateTime(2023, 5, 17, 1, 9, 45, 148, DateTimeKind.Local).AddTicks(4034),
                            Title = "Incredible Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 721.773541800572m,
                            ReleaseDate = new DateTime(2023, 2, 5, 13, 13, 21, 144, DateTimeKind.Local).AddTicks(5601),
                            Title = "Gorgeous Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 688.245783060904m,
                            ReleaseDate = new DateTime(2023, 4, 30, 15, 39, 16, 256, DateTimeKind.Local).AddTicks(817),
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 553.558320945389m,
                            ReleaseDate = new DateTime(2023, 7, 24, 2, 10, 10, 249, DateTimeKind.Local).AddTicks(2117),
                            Title = "Incredible Soft Computer"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 11, 18, 3, 5, 33, 465, DateTimeKind.Local).AddTicks(3897),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 922.479030014704m,
                            ReleaseDate = new DateTime(2023, 10, 14, 1, 31, 22, 662, DateTimeKind.Local).AddTicks(2046),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 7, 24, 21, 18, 48, 601, DateTimeKind.Local).AddTicks(2519),
                            Title = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 955.272407213818m,
                            ReleaseDate = new DateTime(2023, 5, 1, 21, 47, 49, 851, DateTimeKind.Local).AddTicks(8405),
                            Title = "Handcrafted Frozen Keyboard"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 151.982358236323m,
                            ReleaseDate = new DateTime(2022, 11, 28, 15, 3, 37, 690, DateTimeKind.Local).AddTicks(5996),
                            Title = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 434.299358334532m,
                            ReleaseDate = new DateTime(2022, 12, 16, 19, 55, 55, 685, DateTimeKind.Local).AddTicks(5668),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "4",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 57.7988712865854m,
                            ReleaseDate = new DateTime(2023, 1, 5, 14, 29, 53, 218, DateTimeKind.Local).AddTicks(7459),
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 883.980300599234m,
                            ReleaseDate = new DateTime(2023, 4, 3, 6, 3, 6, 614, DateTimeKind.Local).AddTicks(5616),
                            Title = "Handcrafted Rubber Shirt"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 822.452619476455m,
                            ReleaseDate = new DateTime(2023, 1, 13, 4, 4, 46, 933, DateTimeKind.Local).AddTicks(6985),
                            Title = "Rustic Granite Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 22.2432652671092m,
                            ReleaseDate = new DateTime(2023, 4, 9, 11, 43, 1, 493, DateTimeKind.Local).AddTicks(2173),
                            Title = "Sleek Granite Chair"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 6, 27, 8, 29, 18, 116, DateTimeKind.Local).AddTicks(9937),
                            Title = "Incredible Rubber Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 533.504530191656m,
                            ReleaseDate = new DateTime(2023, 8, 9, 15, 34, 40, 265, DateTimeKind.Local).AddTicks(1981),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 265.709933652407m,
                            ReleaseDate = new DateTime(2023, 8, 1, 2, 45, 39, 694, DateTimeKind.Local).AddTicks(7288),
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 294.402654204239m,
                            ReleaseDate = new DateTime(2023, 1, 23, 18, 31, 53, 250, DateTimeKind.Local).AddTicks(6266),
                            Title = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 741.648888164036m,
                            ReleaseDate = new DateTime(2023, 1, 27, 16, 12, 18, 409, DateTimeKind.Local).AddTicks(3890),
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 825.239833488706m,
                            ReleaseDate = new DateTime(2023, 1, 5, 12, 18, 41, 479, DateTimeKind.Local).AddTicks(5404),
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "1",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 305.894089151124m,
                            ReleaseDate = new DateTime(2023, 5, 10, 17, 0, 53, 38, DateTimeKind.Local).AddTicks(8935),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 778.911179241683m,
                            ReleaseDate = new DateTime(2023, 1, 13, 12, 0, 27, 341, DateTimeKind.Local).AddTicks(2075),
                            Title = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 318.709401070936m,
                            ReleaseDate = new DateTime(2023, 2, 25, 8, 52, 44, 767, DateTimeKind.Local).AddTicks(1708),
                            Title = "Handcrafted Metal Mouse"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 463.195345650052m,
                            ReleaseDate = new DateTime(2023, 4, 10, 13, 34, 48, 369, DateTimeKind.Local).AddTicks(913),
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 8, 28, 2, 43, 47, 548, DateTimeKind.Local).AddTicks(9590),
                            Title = "Incredible Plastic Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
